services:
  database:
    image: postgres:16-alpine
    restart: always
    container_name: riftwars-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: riftwars
  api:
    build: .
    container_name: riftwars-api
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/rift-wars-api
    links:
      - database
    depends_on:
      - database
    command: sh -c "/wait; npm ci; npm run db:migrate; npm run dev"
    environment:
      - WAIT_HOSTS=database:5432
      - WAIT_TIMEOUT=1000
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=300
